language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- npm install -g istanbul
- bower install
services:
- mongodb
env:
- MONGO_TEST_URL="mongodb://localhost/test"